language: generic
before_install:
  # Install Pulumi
  - curl -L https://get.pulumi.com/ | bash -s -- --version 0.14.3
  - export PATH=$HOME/.pulumi/bin:$PATH
  - pulumi login
script:
  - ./scripts/travis_${TRAVIS_EVENT_TYPE}.sh
