version: 2.1

orbs:
  pulumi: pulumi/pulumi@dev:0.0.1

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Install before Build to ensure required Node plugins are available.
      - pulumi/login:
          version: "0.16.2"

      # Build
      - run:
          name: Build and Test
          command: |
            npm install
            npm run build
            npm run test

      # Deploy using Pulumi
      - pulumi/update:
          stack: browserhack-demo
